package com.ietf.etfbatch.stock.dto

data class KisPriceDetailOutput (
    var market : String,
    var stockCode : String,
    val rsym : String,
    val zdiv : String,
    val curr : String,
    val vnit : String,
    val open : String,
    val high : String,
    val low : String,
    val last : String,
    val base : String,
    val pvol : String,
    val pamt : String,
    val uplp : String,
    val dnlp : String,
    val h52p : String,
    val h52d : String,
    val l52p : String,
    val l52d : String,
    val perx : String,
    val pbrx : String,
    val epsx : String,
    val bpsx : String,
    val shar : String,
    val mcap : String,
    val tomv : String,
    val t_xprc : String,
    val t_xdif : String,
    val t_xrat : String,
    val t_rate : String,
    val t_xsgn : String,
    val e_ordyn : String,
    val e_hogau : String,
    val e_icod : String,
    val e_parp : String,
    val tvol : String,
    val tamt : String,
    val etyp_nm : String
) {

}